repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: check-yaml
-   repo: https://github.com/wpumacay/cmake-format-precommit
    rev: v0.6.13.dev
    hooks:
    -   id: cmake-format