[build-system]
requires = [
  "setuptools",
  "wheel",
  "ninja",
  "cmake",
]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 80
target-version = ['py39']
include = '\.pyi?$'

[tool.isort]
profile = "black"
