name: ci-linux

on:
  push:
  pull_request:
    branches:
      - master
      - dev

jobs:
  build-gcc:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, ubuntu-latest]
        build-type: [Release, Debug]

    name: "Build: ${{matrix.os}} • ${{matrix.build-type}} • GCC"
    runs-on: ${{matrix.os}}

    steps:
    - uses: actions/checkout@v2

    - name: Update CMake
      uses: jwlawson/actions-setup-cmake@v1.10

    - name: Configure CMake
      env:
        CC: gcc
        CXX: g++
      run: cmake -S . -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.build-type}}

    - name: Build C++ Project
      run: cmake --build ${{github.workspace}}/build --config ${{matrix.build-type}}

    - name: Running C++ Tests
      run: ctest --test-dir ${{github.workspace}}/build/tests/cpp

  build-clang:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, ubuntu-latest]
        build-type: [Release, Debug]

    name: "Build: ${{matrix.os}} • ${{matrix.build-type}} • Clang"
    runs-on: ${{matrix.os}}

    steps:
    - uses: actions/checkout@v2

    - name: Update CMake
      uses: jwlawson/actions-setup-cmake@v1.10

    - name: Configure CMake
      env:
        CC: clang
        CXX: clang++
      run: cmake -S . -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{matrix.build-type}}

    - name: Build C++ Project
      run: cmake --build ${{github.workspace}}/build --config ${{matrix.build-type}}

    - name: Running C++ Tests
      run: ctest --test-dir ${{github.workspace}}/build/tests/cpp
