name: deploy-pypi

on:
  push:
    branches:
      - dev

jobs:
  sdist:
    name: Build source distribution for PyPI upload
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Build package
        run: |
          ls ${{ github.workspace }}
          virtualenv venv && source venv/bin/activate
          pip install -r requirements.txt
          pip install -v .
          pip install twine
          python setup.py sdist

      - name: Upload source distribution to TestPyPI
        env:
          TWINE_USERNAME: ${{ secrets.TEST_PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.TEST_PYPI_PASSWORD }}
        run: |
          twine upload --repository testpypi dist/*

      - name: Upload source distribution to PyPI
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          twine upload dist/*
